"""SQLAlchemy database models."""
from datetime import datetime, date
from typing import Optional
from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Date, Boolean, 
    ForeignKey, Text, Enum, Index, JSON
)
from sqlalchemy.orm import relationship
import enum
from app.database import Base


class Instrument(Base):
    """Futures instrument metadata."""
    __tablename__ = "instruments"
    
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(20), unique=True, nullable=False, index=True)
    name = Column(String(100), nullable=False)
    exchange = Column(String(50))
    tick_size = Column(Float, nullable=False)  # Minimum price movement
    multiplier = Column(Float, nullable=False)  # Contract multiplier
    currency = Column(String(3), default="USD")
    active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    bars = relationship("Bar", back_populates="instrument", cascade="all, delete-orphan")
    features = relationship("Feature", back_populates="instrument", cascade="all, delete-orphan")
    signals = relationship("Signal", back_populates="instrument", cascade="all, delete-orphan")
    orders = relationship("Order", back_populates="instrument", cascade="all, delete-orphan")
    positions = relationship("Position", back_populates="instrument", cascade="all, delete-orphan")


class Bar(Base):
    """OHLCV daily bar data."""
    __tablename__ = "bars"
    
    id = Column(Integer, primary_key=True, index=True)
    instrument_id = Column(Integer, ForeignKey("instruments.id"), nullable=False)
    date = Column(Date, nullable=False, index=True)
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    instrument = relationship("Instrument", back_populates="bars")
    
    __table_args__ = (
        Index('ix_bars_instrument_date', 'instrument_id', 'date', unique=True),
    )


class Feature(Base):
    """Computed technical features."""
    __tablename__ = "features"
    
    id = Column(Integer, primary_key=True, index=True)
    instrument_id = Column(Integer, ForeignKey("instruments.id"), nullable=False)
    date = Column(Date, nullable=False, index=True)
    
    # Features
    atr_20 = Column(Float)
    ma_50 = Column(Float)
    ma_slope_10 = Column(Float)  # 10-day slope of MA50
    hh_20 = Column(Float)  # Highest high last 20 days
    ll_20 = Column(Float)  # Lowest low last 20 days
    hh_10 = Column(Float)  # Highest high last 10 days
    ll_10 = Column(Float)  # Lowest low last 10 days
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    instrument = relationship("Instrument", back_populates="features")
    
    __table_args__ = (
        Index('ix_features_instrument_date', 'instrument_id', 'date', unique=True),
    )


class SignalType(str, enum.Enum):
    """Signal type enumeration."""
    ENTRY_LONG = "entry_long"
    ENTRY_SHORT = "entry_short"
    EXIT_LONG = "exit_long"
    EXIT_SHORT = "exit_short"
    STOP_LONG = "stop_long"
    STOP_SHORT = "stop_short"


class Signal(Base):
    """Trading signals generated by strategy."""
    __tablename__ = "signals"
    
    id = Column(Integer, primary_key=True, index=True)
    instrument_id = Column(Integer, ForeignKey("instruments.id"), nullable=False)
    backtest_run_id = Column(Integer, ForeignKey("backtest_runs.id"), nullable=True)
    date = Column(Date, nullable=False, index=True)
    signal_type = Column(Enum(SignalType), nullable=False)
    
    # Signal details
    price = Column(Float)  # Reference price when signal generated
    target_contracts = Column(Integer, default=0)
    stop_price = Column(Float)
    reason = Column(String(200))
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    instrument = relationship("Instrument", back_populates="signals")
    backtest_run = relationship("BacktestRun", back_populates="signals")


class OrderStatus(str, enum.Enum):
    """Order status enumeration."""
    PENDING = "pending"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


class OrderSide(str, enum.Enum):
    """Order side enumeration."""
    BUY = "buy"
    SELL = "sell"


class Order(Base):
    """Trade orders."""
    __tablename__ = "orders"
    
    id = Column(Integer, primary_key=True, index=True)
    instrument_id = Column(Integer, ForeignKey("instruments.id"), nullable=False)
    backtest_run_id = Column(Integer, ForeignKey("backtest_runs.id"), nullable=True)
    signal_id = Column(Integer, ForeignKey("signals.id"), nullable=True)
    
    order_date = Column(Date, nullable=False, index=True)
    side = Column(Enum(OrderSide), nullable=False)
    quantity = Column(Integer, nullable=False)
    order_type = Column(String(20), default="MARKET")
    limit_price = Column(Float)
    stop_price = Column(Float)
    status = Column(Enum(OrderStatus), default=OrderStatus.PENDING)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    instrument = relationship("Instrument", back_populates="orders")
    backtest_run = relationship("BacktestRun", back_populates="orders")
    fills = relationship("Fill", back_populates="order", cascade="all, delete-orphan")


class Fill(Base):
    """Order fills/executions."""
    __tablename__ = "fills"
    
    id = Column(Integer, primary_key=True, index=True)
    order_id = Column(Integer, ForeignKey("orders.id"), nullable=False)
    backtest_run_id = Column(Integer, ForeignKey("backtest_runs.id"), nullable=True)
    
    fill_date = Column(Date, nullable=False, index=True)
    fill_price = Column(Float, nullable=False)
    quantity = Column(Integer, nullable=False)
    commission = Column(Float, default=0)
    slippage = Column(Float, default=0)  # In ticks
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    order = relationship("Order", back_populates="fills")
    backtest_run = relationship("BacktestRun", back_populates="fills")


class Position(Base):
    """Current positions."""
    __tablename__ = "positions"
    
    id = Column(Integer, primary_key=True, index=True)
    instrument_id = Column(Integer, ForeignKey("instruments.id"), nullable=False)
    backtest_run_id = Column(Integer, ForeignKey("backtest_runs.id"), nullable=True)
    
    date = Column(Date, nullable=False, index=True)
    quantity = Column(Integer, nullable=False)  # Positive for long, negative for short
    entry_price = Column(Float, nullable=False)
    current_price = Column(Float)
    stop_price = Column(Float)
    unrealized_pnl = Column(Float, default=0)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    instrument = relationship("Instrument", back_populates="positions")
    backtest_run = relationship("BacktestRun", back_populates="positions")


class PortfolioSnapshot(Base):
    """Daily portfolio snapshots."""
    __tablename__ = "portfolio_snapshots"
    
    id = Column(Integer, primary_key=True, index=True)
    backtest_run_id = Column(Integer, ForeignKey("backtest_runs.id"), nullable=True)
    
    date = Column(Date, nullable=False, index=True)
    equity = Column(Float, nullable=False)
    cash = Column(Float, nullable=False)
    unrealized_pnl = Column(Float, default=0)
    realized_pnl = Column(Float, default=0)
    daily_pnl = Column(Float, default=0)
    drawdown = Column(Float, default=0)
    
    # Risk metrics
    total_exposure = Column(Float, default=0)
    num_positions = Column(Integer, default=0)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    backtest_run = relationship("BacktestRun", back_populates="portfolio_snapshots")


class BacktestRun(Base):
    """Backtest run configuration and results."""
    __tablename__ = "backtest_runs"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(200), nullable=False)
    description = Column(Text)
    
    # Date range
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)
    
    # Configuration (stored as JSON)
    config = Column(JSON, nullable=False)
    
    # Results summary
    initial_capital = Column(Float, nullable=False)
    final_equity = Column(Float)
    total_return = Column(Float)
    cagr = Column(Float)
    sharpe_ratio = Column(Float)
    sortino_ratio = Column(Float)
    max_drawdown = Column(Float)
    max_drawdown_duration = Column(Integer)  # Days
    win_rate = Column(Float)
    profit_factor = Column(Float)
    total_trades = Column(Integer)
    
    # Status
    status = Column(String(20), default="pending")  # pending, running, completed, failed
    error_message = Column(Text)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime)
    
    # Relationships
    signals = relationship("Signal", back_populates="backtest_run", cascade="all, delete-orphan")
    orders = relationship("Order", back_populates="backtest_run", cascade="all, delete-orphan")
    fills = relationship("Fill", back_populates="backtest_run", cascade="all, delete-orphan")
    positions = relationship("Position", back_populates="backtest_run", cascade="all, delete-orphan")
    portfolio_snapshots = relationship("PortfolioSnapshot", back_populates="backtest_run", cascade="all, delete-orphan")


class JournalEntry(Base):
    """Trading journal entries."""
    __tablename__ = "journal_entries"
    
    id = Column(Integer, primary_key=True, index=True)
    date = Column(Date, nullable=False, index=True)
    title = Column(String(200), nullable=False)
    content = Column(Text, nullable=False)
    tags = Column(String(500))  # Comma-separated tags
    
    # Optional links
    signal_id = Column(Integer, ForeignKey("signals.id"), nullable=True)
    order_id = Column(Integer, ForeignKey("orders.id"), nullable=True)
    backtest_run_id = Column(Integer, ForeignKey("backtest_runs.id"), nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

